# This is a basic workflow to help you get started with Actions

name: 'Plan VPC'

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ stg ]
    paths:
    - "Sesion3_Infra_Reinaldo/deploy-infra/**"
    - "!Sesion3_Infra_Reinaldo/deploy-infra/.github/**"
    - "!.github/**"
    - "!.gitignore"
    - "!.pre-commit-config.yaml"
    - "!README.md"
      
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform:
    name: 'terraform plan deploy-infra/vpc'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Configure aws credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ARN_ROLE }}
          role-session-name: infrastructuresession
          aws-region: eu-west-3

      # Runs terraform stack VPC
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Init VPC'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'Sesion3_Infra_Reinaldo/deploy-infra/vpc'
          tf_actions_comment: true
      - name: 'Terraform fmt VPC'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: 'Sesion3_Infra_Reinaldo/deploy-infra/vpc'
          tf_actions_comment: true
      - name: 'Terraform plan VPC'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.2
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'Sesion3_Infra_Reinaldo/deploy-infra/vpc'
          tf_actions_comment: true